from django.urls import path
from .import views
from .views import SetCookie, GetCookie

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('services/', views.services, name='services'),
    path('projects/', views.projects, name='projects'),
    path('faq/', views.faq, name='faq'),
    path('team/', views.team, name='team'),
    path('success/', views.success, name='success'),
    path('more/', views.more, name='more'),
    path('advisory/', views.advisory, name='advisory'),
    path('digital/', views.digital, name='digital'),
    path('data/', views.data, name='data'),
    path('design/', views.design, name='design'),
    path('it/', views.it, name='it'),
    path('training/', views.training, name='training'),
    path('content/', views.content, name='content'),
    path('terms/', views.terms, name='terms'),
    path('privacy/', views.privacy, name='privacy'),
    path('boost/', views.boost, name='boost'),
    path('mobile/', views.mobile, name='mobile'),
    path('cyber/', views.cyber, name='cyber'),
    path('software/', views.software, name='software'),
    path('team-detail/', views.team_detail, name='team-detail'),
    path('team-kingsley/', views.team_detail_kingsley, name='team-kingsley'),
    path('team-ify/', views.team_ify, name='team-ify'),
    path('team-dan/', views.team_dan, name='team-dan'),
    path('team-timi/', views.team_timi, name='team-timi'),
    path('team-ndeya/', views.team_ndeya, name='team-ndeya'),
    path('team-victor/', views.team_victor, name='team-victor'),
    path('team-ben/', views.team_ben, name='team-ben'),
    path('team-bode/', views.team_bode, name='team-bode'),
    path('team-adrar/', views.team_adrar, name='team-adrar'),
    path('animate/', views.animate, name='animate'),
    path('pricing/', views.pricing, name='pricing'),
    path('pricing-main/', views.pricing_main, name='pricing-main'),
    path('main/', views.send_request, name='main'),
    path('maint/', views.send_request1, name='maint'),
    path('success-page/', views.success_main, name='success-page'),
    path('site-price/', views.site_price, name='site-price'),
    path('site-main/', views.site_main, name='site-main'),
    path('site-maint/', views.site_maint, name='site-maint'),

    path('setcookie/', SetCookie),
    path('getcookie/', GetCookie),

]