# Generated by Django 3.1.7 on 2021-02-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(default='pix.jpeg', null=True, upload_to='pic'),
        ),
    ]
