# Generated by Django 3.1.7 on 2021-02-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(default='pix.jpeg', help_text='Recommended size 800x500 for detail and 400x200 index', null=True, upload_to='pic'),
        ),
    ]
